### ISSUE TITLE
loc_inference training

### ISSUE THREAD

**Issue by lifeifei-airs** [haksorus/gsplatloc#3]
Thanks for sharing; it's great work! I'm wondering, in the loc inference step, why do you use the image rendered from the view of the coarse step in each warp iteration to calculate the warp loss, instead of updating the rendered image using t_opt, quat_opt?

**Comment by haksorus** [comment]
Hello, @lifeifei-airs! 

Thank you for your interest in our work. The reason is that the coarse pose is quite close to the query image pose, so additional rendering in the warp loop does not make significant changes to the localization process. On the other hand, frequent rendering requires high computational costs.

**Comment by lifeifei-airs** [comment]
Got it, thank you very much！
